# Generated by Django 4.2.1 on 2023-05-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_song_audio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='uploaded_by',
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
