# Generated by Django 4.2.1 on 2023-05-27 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_song_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='user',
        ),
    ]
